import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import LayoutComponent from "@/components/LayoutComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets:["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto"
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${roboto.variable}  antialiased`}
      >
        <div className=" w-screen flex flex-row items-center justify-center h-24 bg-white z-50 fixed border-solid border-b-[1px] border-primary_border">
          <div className=" w-4/5 flex flex-row justify-between items-center h-full ">
            <h1>Exclusive</h1>
              <ul className=" flex flex-row justify-between items-center w-1/3">
                <li className=" active:underline cursor-pointer">
                  Home
                </li>
                <li className=" active:underline cursor-pointer">
                  Contact
                </li>
                <li className=" active:underline cursor-pointer">
                  About
                </li>
                <li className=" active:underline cursor-pointer">
                  Signup
                </li>
              </ul>
              <LayoutComponent />

          </div>
        </div>
        <main className=" pt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
